name: Check or publish

on:
  push:
    branches:
      - main
      - release
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2

      - run: deno task ci

  publish:
    needs: check
    if: ${{ github.ref_name == 'release' && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2

      - run: deno publish
